DROP TABLE IF EXISTS ROUTE;

CREATE TABLE ROUTE
(
    ID             INT PRIMARY KEY NOT NULL,
    DEPARTURE_CODE VARCHAR(100)    NOT NULL,
    ARRIVAL_CODE   VARCHAR(100)    NOT NULL,
    DURATION       INT             NOT NULL
);